CREATE TABLE `Posts` (
    `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    `AuthorID` INTEGER NOT NULL,
    `Url` TEXT NOT NULL,
    `CreatedAt` DATE NOT NULL,
    `Description` TEXT, `Tags` TEXT,
    FOREIGN KEY(`AuthorID`) REFERENCES Users(ID)
);

CREATE TABLE `Users` (
    `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    `Email` TEXT NOT NULL,
    `Password` TEXT NOT NULL,
    `DisplayName` TEXT NOT NULL
);